### ISSUE TITLE
issue-01-a E59

### ISSUE THREAD

**Issue by marchaya** [Clubs-At-Manoa/e59#1]

**Comment by cleoso** [comment]
https://courses.ics.hawaii.edu/ics314s24/morea/deployment/experience-test-deployment-digital-ocean.html

Submission
By the date and time indicated on the Calendar page, please finish all of these steps. Create three screenshots:

Your Meteor application (retrieved using a URL like “https://111.222.333.444”).
Your Studio3T screen showing a connection to your Meteor application.
Your MontiAPM dashboard, showing a connection to your Meteor application.
Post them to the #deployment channel.

**Comment by JennieCab** [comment]
Marc posted to deployment channel 4/9.
